export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const SET_API_DATA = "SET_API_DATA";
export const SET_USER_INPUT = "SET_USER_INPUT";
export const ADD_CHARACTER = "ADD_CHARACTER";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const LIKE_CHARACTER = "LIKE_CHARACTER";
export const SET_SCREEN_MODE = "SET_SCREEN_MODE";
